# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
version: '3.3'

services:

  frontend:
    build: ./web/frontend    
    ports:
      - "8081:8081"
    depends_on:
      - db
  backend:
    build: ./web/backend
    ports:
      - "8088:80"
    depends_on:
      - db


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: devtool_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - ./web/db/my-db:/var/lib/mysql
volumes:
  db_data: